### ベースの設定
@baseURL = http://localhost:8080/api
@headers = Content-Type: application/x-www-form-urlencoded; charset=UTF-8
@access_token = Authorization: Bearer 1|cZKjkb9rN9Nuho3WgVSen5IM06H0B7SmDf1AG9xCd4430458
@refresh_token = TlMwm7nrmfzjc7A05iER17oaqJckD9xWn6tW7lTizptdUp3r5ZLJ5t46vx0H7YIK

### ログイン用API
POST {{baseURL}}/login
{{headers}}

email=admin@example.com
&password=password
&device_name=iphone3

### リフレッシュトークン更新API
POST {{baseURL}}/refresh
{{headers}}

refresh_token={{refresh_token}}
&device_name=iphone3

### ログアウト用API
POST {{baseURL}}/logout
{{access_token}}
{{headers}}

email=admin@example.com
&password=password
&device_name=iphone3


### ログイン情報表示API
GET {{baseURL}}/me
{{access_token}}
{{headers}}