@baseURL = http://localhost:8080/api
@headers = Content-Type: application/x-www-form-urlencoded; charset=UTF-8
@access_token = <your_access_token_here>
@refresh_token = <your_refresh_token_here>
@access_token_header = Authorization: Bearer {{access_token}}

### 顧客登録API
POST {{baseURL}}/customers/regist
{{access_token_header}}
{{headers}}

co_name=テスト株式会社2
&co_address=東京都渋谷区2-3-4
&tanto_name=山田太郎
&tanto_tel=090-1234-5678

### 顧客更新API
POST {{baseURL}}/customers/update
{{access_token_header}}
{{headers}}

co_cd=2
&co_name=テスト株式会社1
&co_address=東京都渋谷区2-2-3
&tanto_name=山田太郎
&tanto_tel=090-1234-1111

### 顧客削除API
POST {{baseURL}}/customers/delete
{{access_token_header}}
{{headers}}

co_cd=1

### 顧客一覧API
GET {{baseURL}}/customers/list
{{access_token_header}}
{{headers}}