@baseURL = http://localhost:8081/api
@headers = Content-Type: application/x-www-form-urlencoded; charset=UTF-8
@accept_json = Accept: application/json
@access_token = <your_access_token_here>
@refresh_token = <your_refresh_token_here>
@access_token_header = Authorization: Bearer {{access_token}}

### 顧客登録API
POST {{baseURL}}/customers/regist
{{access_token_header}}
{{headers}}
{{accept_json}}

co_name=為国株式会社
&co_address=東京都渋谷区2-3-4
&tanto_name=山田太郎
&tanto_tel=090-1234-5666
&memo_title=初回面談メモ
&memo_content=初回面談では、今後の取引について前向きな話ができました。
&tag_cd[]=1


### 顧客更新API
POST {{baseURL}}/customers/update
{{access_token_header}}
{{headers}}
{{accept_json}}

co_cd=3
&co_name=テスト株式会社12
&co_address=東京都渋谷区2-2-3
&tanto_name=山田太郎
&tanto_tel=090-1234-1111
&memo_title=初回面談メモ更新
&memo_content=初回面談では、今後の取引について前向きな話ができました。内容を更新しました。

### 顧客削除API
POST {{baseURL}}/customers/delete
{{access_token_header}}
{{headers}}
{{accept_json}}

co_cd=1

### 顧客一覧API
GET {{baseURL}}/customers/list
{{access_token_header}}
{{headers}}
{{accept_json}}