@baseURL = http://localhost:8081/api
@headers = Content-Type: application/x-www-form-urlencoded; charset=UTF-8
@accept_json = Accept: application/json
@access_token = <your_access_token_here>
@refresh_token = <your_refresh_token_here>
@access_token_header = Authorization: Bearer {{access_token}}

### タグ更新API
POST {{baseURL}}/tags/update
{{access_token_header}}
{{headers}}
{{accept_json}}

co_cd=1
&memo_cd=2
&title=初回面談メモ更新
&content=初回面談では、今後の取引について前向きな話ができました。内容を更新しました。

### タグ削除API
POST {{baseURL}}/tags/delete
{{access_token_header}}
{{headers}}
{{accept_json}}

co_cd=1
&memo_cd=1

### タグ一覧API
GET {{baseURL}}/tags/list/1
{{access_token_header}}
{{headers}}
{{accept_json}}

### タグ登録API
POST {{baseURL}}/tags/regist
{{access_token_header}}
{{headers}}
{{accept_json}}

tag_name=話を聞いていくれる
